import type { AppSettings, ConversationMeta } from '../../shared/types'
import { DEFAULT_CUSTOM_COLORS } from '../../shared/appearance'

export function makeAppSettings(overrides: Partial<AppSettings> = {}): AppSettings {
  return {
    ollamaBaseUrl: 'http://localhost:11434',
    defaultModelRef: null,
    defaultPermissionMode: 'accept-edits',
    disabledBuiltins: [],
    artifactReviewPolicy: 'request-review',
    defaultEffort: 'adaptive',
    defaultThinking: true,
    sidebarGroupBy: 'project',
    sidebarSort: 'updated',
    sidebarShowArchived: false,
    sidebarSubtitle: 'none',
    theme: 'dark',
    customColors: DEFAULT_CUSTOM_COLORS,
    fontSize: 'medium',
    conversationWidth: 'default',
    reduceMotion: false,
    chatFont: 'sans',
    modelPricing: {},
    modelPricingSyncedAt: 0,
    sttBackend: 'openai',
    profileName: '',
    profileCallMe: '',
    customInstructions: '',
    disabledModels: [],
    enabledLiveModels: [],
    customModels: [],
    securityPreset: 'custom',
    fileAccessPolicy: 'deny',
    terminalAutoExec: 'auto',
    browserEnabled: false,
    browserAllowlist: [],
    browserBlocklist: [],
    mcpEnabled: false,
    mcpEnabledServers: [],
    mcpTrustedProjectServers: {},
    mcpUntrustedGlobalServers: [],
    mcpSpawnConsented: [],
    mcpTrustedPluginServers: [],
    githubClientId: '',
    skillsDisabledGlobal: [],
    skillsDisabledProject: {},
    pluginsEnabled: [],
    marketplaces: [],
    hooksDisabledGlobal: [],
    hooksConsented: [],
    ursaEnabled: false,
    ursaInstructions: '',
    ursusEnabled: false,
    ursusInstructions: '',
    hermesEnabled: false,
    hermesGatewayUrl: '',
    hermesConnectionMode: 'legacy',
    hermesNativeUrl: '',
    hermesLabel: 'Hermes',
    hermesIcon: 'IconChat',
    ...overrides
  }
}

export function makeConversationMeta(overrides: Partial<ConversationMeta> = {}): ConversationMeta {
  return {
    id: 'conversation',
    projectPath: null,
    title: null,
    modelRef: null,
    createdAt: 0,
    updatedAt: 0,
    permissionMode: 'accept-edits',
    activeRules: [],
    effort: 'adaptive',
    thinking: true,
    webSearch: false,
    ursaMode: 'code',
    hermesSessionId: null,
    hermesMode: 'legacy',
    projectId: null,
    pinned: false,
    archived: false,
    environment: 'local',
    worktrees: [],
    ...overrides
  }
}
